server:
  port: 8071
spring:
  application:
    name: "config-server"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          search-locations: "file:///home//yaroslav//Documents//config"