services:
  network-deploy-service:
    networks:
      - network_ms

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 768m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-config-server-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"