# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eureka-server-deployment
serviceName: eureka-server
appLabel: eureka-server
appName: eureka-server

replicaCount: 1

image:
  repository: niochronos/eureka-server
  tag: s14

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
dataSource_enabled: false